#!/usr/bin/env php

<?php
$localPath = __DIR__ . '/vendor/autoload.php';
$vendorPath = __DIR__ . '/../../autoload.php';

if (file_exists($localPath)) {
    require $localPath;
} else {
    require $vendorPath;
}

(new \Fetzi\PhpspecWatcher\WatcherApplication)->run();